# Generated by Django 4.2.16 on 2025-06-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("point", "ポイント支払い")], max_length=50, unique=True
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
