# Generated by Django 4.2.16 on 2025-06-02 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="coupons", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
