# Generated by Django 4.2.13 on 2025-06-03 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("items", "0002_item_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recommendation",
            old_name="recommended_by",
            new_name="recommended_to",
        ),
        migrations.AlterUniqueTogether(
            name="recommendation", unique_together={("item", "recommended_to")},
        ),
        migrations.AddField(
            model_name="recommendation",
            name="recommended_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
